# Generated by Django 3.0.4 on 2020-03-22 10:38

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Smallbus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='this is content of the package')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('view_count', models.IntegerField(default=0)),
                ('featured', models.BooleanField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='This is a detail of the pacakges')),
                ('categories', models.ManyToManyField(to='grantha.Category')),
                ('next_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='grantha.Package')),
                ('previous_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='grantha.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('bus_name', models.CharField(max_length=100)),
                ('ac_rate', models.IntegerField(default=0)),
                ('non_rate', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('allowance', models.IntegerField(default=0)),
                ('night_allowance', models.IntegerField(default=0)),
                ('smallbus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grantha.Smallbus')),
            ],
        ),
    ]
