# Generated by Django 3.0.4 on 2020-03-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallbus',
            name='title',
            field=models.CharField(default='Title', max_length=100),
            preserve_default=False,
        ),
    ]
