# Generated by Django 3.0.4 on 2020-03-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grantha', '0002_smallbus_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='smallbus',
        ),
        migrations.DeleteModel(
            name='Smallbus',
        ),
    ]
