# Generated by Django 3.0.4 on 2020-03-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantha', '0005_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('comment', models.TextField(default='comment of the clients.')),
            ],
        ),
    ]
