# Generated by Django 3.0.4 on 2020-03-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantha', '0006_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='featured',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
    ]
