# Generated by Django 3.0.4 on 2020-03-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantha', '0007_testimonial_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='featured',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
    ]
