# Generated by Django 3.0.4 on 2020-03-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grantha', '0008_about_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=50)),
                ('featured', models.BooleanField()),
            ],
        ),
    ]
